---
title: "Ezperanza_matematica_moneda"
author: "Dennis290699"
date: "11/1/2023"
output: word_document
---

## SIMULACION DE VARIABLES ALEATORIAS DISCRETAS Y ESPERANZA

 Ejemplo.- Lanzamiento de una moneda. Sea X v. a, el numero 
 que se muestra en la cara del dado, X = cara, sello.
 
```{r}
X <- 1:2
  probabilidad <-c(1/2, 1/2)
  plot(X, probabilidad, xlab ="Numero de cara en el dado",
        ylab = "Probabilidad",  type = "h")
```

```{r}
#Calculemos la esperanza
esperanza <- sum(X*probabilidad)
esperanza
```
 
```{r}
moneda <- sample(c(1:2), 60, replace = TRUE)
mean(moneda)
varianza <- sum((moneda - mean(moneda))**2) / 60
# Aumentamos el numero de simulaciones
moneda2 <- sample(c(1:2), 20000, replace = TRUE)
table(moneda2)
# Calculamos las probabilidades con las frecuencias relativas
round(table(moneda2)/20000, 2)
```

```{r}
#Grafiquemos esas probabilidades
plot(table(moneda2)/20000, xlab = "Numero en cara de dado",
     ylab = "Probabilidad", type = "h")

plot(X, probabilidad, xlab ="Numero de cara en el dado",
        ylab = "Probabilidad",  type = "h");
```
 
 